<!DOCTYPE html>
<!--[if IE]><![endif]-->
<html>
  
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Python example </title>
    <meta name="viewport" content="width=device-width">
    <meta name="title" content="Python example ">
    <meta name="generator" content="docfx 2.59.0.0">
    
    <link rel="shortcut icon" href="../favicon.ico">
    <link rel="stylesheet" href="../styles/docfx.vendor.css">
    <link rel="stylesheet" href="../styles/docfx.css">
    <link rel="stylesheet" href="../styles/main.css">
    <meta property="docfx:navrel" content="../toc.html">
    <meta property="docfx:tocrel" content="toc.html">
    
    
    
  </head>
  <body data-spy="scroll" data-target="#affix" data-offset="120">
    <div id="wrapper">
      <header>
        
        <nav id="autocollapse" class="navbar navbar-inverse ng-scope" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              
              <a class="navbar-brand" href="../index.html">
                <img id="logo" class="svg" src="../logo.svg" alt="">
              </a>
            </div>
            <div class="collapse navbar-collapse" id="navbar">
              <form class="navbar-form navbar-right" role="search" id="search">
                <div class="form-group">
                  <input type="text" class="form-control" id="search-query" placeholder="Search" autocomplete="off">
                </div>
              </form>
            </div>
          </div>
        </nav>
        
        <div class="subnav navbar navbar-default">
          <div class="container hide-when-search" id="breadcrumb">
            <ul class="breadcrumb">
              <li></li>
            </ul>
          </div>
        </div>
      </header>
      <div role="main" class="container body-content hide-when-search">
        
        <div class="sidenav hide-when-search">
          <a class="btn toc-toggle collapse" data-toggle="collapse" href="#sidetoggle" aria-expanded="false" aria-controls="sidetoggle">Show / Hide Table of Contents</a>
          <div class="sidetoggle collapse" id="sidetoggle">
            <div id="sidetoc"></div>
          </div>
        </div>
        <div class="article row grid-right">
          <div class="col-md-10">
            <article class="content wrap" id="_content" data-uid="">
<h1 id="python-example"><strong>Python example</strong></h1>

<pre><code class="lang-python"># Import Rhino.Geometry
import Rhino.Geometry as rg

# Import Robot Components
import clr
clr.AddReference(&quot;RobotComponents.dll&quot;)
import RobotComponents as rc
from RobotComponents.Enumerations import *

# Construct a tool
tcp = rg.Plane(rg.Point3d(0, 0, 250), rg.Vector3d(0, 0, 1))
cone = rg.Cone(tcp, -tcp.Origin.Z, 55)
cone_mesh = rg.Mesh.CreateFromCone(cone, 100, 100)
tool = rc.Definitions.RobotTool(&quot;tool1&quot;, cone_mesh, rg.Plane.WorldXY, tcp)

# Construct a robot preset
robot = rc.Definitions.Robot.GetRobotPreset(RobotPreset.IRB4600_40_255, rg.Plane.WorldXY, tool)

# Fabricatoin settings
speed_low = rc.Actions.SpeedData(&quot;speed_low&quot;, 20)
speed_high = rc.Actions.SpeedData(&quot;speed_high&quot;, 250)
zone_precise = rc.Actions.ZoneData.GetPredefinedZoneData(PredefinedZoneData.fine)
zone_flyover = rc.Actions.ZoneData.GetPredefinedZoneData(PredefinedZoneData.z10)
offset = 100
do_name = &quot;DO_01&quot;

# Create the actions
actions = []

# Configuration control
actions.append(rc.Actions.JointConfigurationControl(True))
actions.append(rc.Actions.LinearConfigurationControl(False))

# Home position
rob_joint = rc.Actions.RobotJointPosition(0, 0, 0, 0, 45, 0)
home_target = rc.Actions.JointTarget(rob_joint)
go_home = rc.Actions.Movement(MovementType.MoveAbsJ, home_target, speed_high, zone_flyover)
actions.append(go_home)

# Follow curves
for i in range(len(curves)):
    
    ## Reverse one another
    if (i % 2): 
        curves[i].Reverse()
       
    ## Curve parameters
    t = curves[i].DivideByCount(10, True)
    
    ## Comments
    actions.append(rc.Actions.CodeLine(&quot; &quot;, CodeType.Instruction))
    actions.append(rc.Actions.Comment(&quot;New curve&quot;, CodeType.Instruction))
    
    ## Follow curves with precise linear movements
    for j in range(len(t)):
        point = curves[i].PointAt(t[j])
        dum, u, v = surface.ClosestPoint(point)
        
        x_axis = curves[i].TangentAt(t[j])
        z_axis = surface.NormalAt(u, v)
        y_axis = rg.Vector3d.CrossProduct(x_axis, z_axis)
        plane = rg.Plane(point, x_axis, y_axis)
        
        ## Above start
        if (j == 0):
            vector = -plane.ZAxis
            vector.Unitize()
            plane_start = rg.Plane(plane.Origin, plane.XAxis, plane.YAxis)
            plane_start.Translate(vector * offset)
            
            target = rc.Actions.RobotTarget(&quot;curve_{}_start&quot;.format(i), plane_start)
            move = rc.Actions.Movement(MovementType.MoveJ, target, speed_high, zone_flyover)
            actions.append(move)
        
        target = rc.Actions.RobotTarget(&quot;curve_{}_{}&quot;.format(i, j), plane)
        move = rc.Actions.Movement(MovementType.MoveL, target, speed_low, zone_precise)
        actions.append(move)
        
        ## Enable digital output
        if (j == 0):
            actions.append(rc.Actions.DigitalOutput(do_name, True))
    
    # Disable digital output
    actions.append(rc.Actions.DigitalOutput(do_name, False))
    
    ## Above end
    vector = -plane.ZAxis
    vector.Unitize()
    plane_end = rg.Plane(plane.Origin, plane.XAxis, plane.YAxis)
    plane_end.Translate(vector * offset)
            
    target = rc.Actions.RobotTarget(&quot;curve_{}_end&quot;.format(i), plane_end)
    move = rc.Actions.Movement(MovementType.MoveL, target, speed_low, zone_precise)
    actions.append(move)
    
# Home position
actions.append(go_home)

# Create the RAPID program
rapid_generator = rc.Actions.RAPIDGenerator(robot, actions, &quot;MainModule&quot;, &quot;BASE&quot;, &quot;main&quot;)
program = rapid_generator.CreateProgramModule()
system = rapid_generator.CreateSystemModule()

</code></pre>
</article>
          </div>
          
          <div class="hidden-sm col-md-2" role="complementary">
            <div class="sideaffix">
              <div class="contribution">
                <ul class="nav">
                  <li>
                    <a href="https://github.com/RobotComponents/RobotComponents-API-Documentation/blob/master/examples/python.md/#L1" class="contribution-link">Improve this Doc</a>
                  </li>
                </ul>
              </div>
              <nav class="bs-docs-sidebar hidden-print hidden-xs hidden-sm affix" id="affix">
                <h5>In This Article</h5>
                <div></div>
              </nav>
            </div>
          </div>
        </div>
      </div>
      
      <footer>
        <div class="grad-bottom"></div>
        <div class="footer">
          <div class="container">
            <span class="pull-right">
              <a href="#top">Back to top</a>
            </span>
            
            <span>Generated by <strong>DocFX</strong></span>
          </div>
        </div>
      </footer>
    </div>
    
    <script type="text/javascript" src="../styles/docfx.vendor.js"></script>
    <script type="text/javascript" src="../styles/docfx.js"></script>
    <script type="text/javascript" src="../styles/main.js"></script>
  </body>
</html>
